### PR TITLE
fix(frontend): keyboard controls for parameter sliders

### LINKED ISSUE #596: Parameter sliders don't work from the keyboard any more
In the Simulations sidebar, I can click on a parameter slider in order to focus it, or Tab to it with the keyboard, but I can't change the value of the focused slider with the left/right cursor keys.

[WCAG 2.2, Success Criterion 2.1.1: Keyboard (Level A)](https://www.w3.org/WAI/WCAG22/Understanding/keyboard).

A parameter slider in the Simulations sidebar, which has keyboard focus.

### PR DESCRIPTION
**Pull request by eatyourgreens**
Fix parameter sliders, in simulation plots, so that they can be controlled from the keyboard. Left/right cursor keys for fine control. Shift+left/right cursor keys for coarse control.

- closes #596.

### CODE REVIEW

File: frontend-v2/src/features/simulation/SimulationSliderView.tsx [hunk 1]
```diff
@@ -231,8 +231,10 @@ const SimulationSliderView: FC<SimulationSliderProps> = ({
           min={minValue}
           max={maxValue}
           step={stepValue}
+          shiftStep={stepValue * 10}
           onChange={handleSliderChange}
-          onChangeCommitted={handleBlur}
```
Comment (eatyourgreens) [inline frontend-v2/src/features/simulation/SimulationSliderView.tsx:235]: `onChangeCommitted` works for pointer events, but commits changes on every slider step when you use the keyboard. 🤷‍♂️
